name: CI

on: push

jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.7', '3.8', '3.9']            
    runs-on: ${{ matrix.os }}
    steps:
      - name: report
        run: echo ${{ matrix.os }} ${{ matrix.python }} ${{ strategy.job-index }} $${{ strategy.job-total }}

