name: CI

on: push

jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.7', '3.8', '3.9']            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download
        if: strategy.job-index != 0
        uses: actions/download-artifact@v2.0.8
        with: 
          name: report.txt
      - name: report
        run: | 
          echo "${{ matrix.os }}/Py${{ matrix.python }}" >> report.txt
      - name: Upload 
        uses: actions/upload-artifact@v2.2.2
        with:
          name: report.txt
