name: CI

on: push

jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.7', '3.8', '3.9']            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: report
        run: | 
          echo OS = ${{ matrix.os }} 
          echo Python = Py${{ matrix.python }} 
          echo Job index = ${{ strategy.job-index }} 
          echo Jobs = $${{ strategy.job-total }}
